blank_issues_enabled: false
contact_links:
  - name: 💬 Drush Slack
    url: https://drupal.slack.com/archives/C039UV0CQBZ
    about: Join the CivicTheme Community to talk, exchange experiences or ask and answer questions.
  - name: 💧 Drupal.org
    url: https://www.drupal.org/project/civictheme
    about: Submit an issue for Drupal theme
