name: Test

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install NPM dependencies
        run: npm install && npx playwright install && npm --prefix components-sdc install

      - name: Install PHP dependencies
        run: composer install

      - name: Check coding standards
        run: npm run lint

      - name: Check Twig coding standards
        run: composer lint

      - name: Build
        run: npm run build && npm run --prefix components-sdc build

      - name: Check snapshots
        run: npm run diff:snapshot

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.job}}-code-coverage-report-${{ matrix.node-version }}
          path: ./.logs/coverage
          if-no-files-found: error

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          files: ./.logs/coverage/clover.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy Twig Components to Netlify
        if: matrix.node-version == 22
        uses: nwtgck/actions-netlify@v3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: './storybook-static'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: 'components-twig'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        timeout-minutes: 1
      - name: Deploy SDC Components Storybook to Netlify
        if: matrix.node-version == 22
        uses: nwtgck/actions-netlify@v3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: './components-sdc/storybook-static'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: 'components-sdc'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        timeout-minutes: 1
