name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for comparing with main branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install && npx playwright install

      - name: Build Storybook
        run: npm run build

      - name: Run visual regression tests
        run: |
          # Capture screenshots for the main branch components
          npm run diff:command -- capture --source main --target components --force
          
          # Capture screenshots for the current branch components
          npm run diff:command -- capture --source current --target components --force
          
          # Capture screenshots for the current branch SDC components
          npm run diff:command -- capture --source current --target components-sdc --force
          
          # List the available screenshot sets
          npm run diff:command -- list --sets
          
          # Compare main vs current branch components
          SOURCE_NAME=$(npm run diff:command -- list --sets | grep "set--main--twig" | awk '{print $2}')
          TARGET_NAME=$(npm run diff:command -- list --sets | grep "set--current--" | grep "twig" | awk '{print $2}')
          npm run diff:command -- compare --source "$SOURCE_NAME" --target "$TARGET_NAME" --force
          
          # Compare main vs current branch SDC components
          SOURCE_SDC_NAME=$(npm run diff:command -- list --sets | grep "set--current--" | grep "twig" | awk '{print $2}')
          TARGET_SDC_NAME=$(npm run diff:command -- list --sets | grep "set--current--" | grep "sdc" | awk '{print $2}')
          npm run diff:command -- compare --source "$SOURCE_SDC_NAME" --target "$TARGET_SDC_NAME" --force

      - name: Upload visual regression reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-reports
          path: |
            visual-diff/screenshots/diff--*
            visual-diff/config/config.json
          if-no-files-found: warn

      - name: Comment on PR with visual regression results
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: createVisualRegressionPrComments } = await import('${{ github.workspace }}/.github/action-scripts/create-visual-regression-pr-comments.js')
            createVisualRegressionPrComments({github, context, require})
          
          
          

